---

- name: update and upgrade packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: remove unneeded dependencies
  become: true
  apt:
    autoremove: yes

- name: install dependencies
  become: true
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: Create a backend folder
  shell: |
    mkdir backend
  args:
    chdir: ~/

- name: unarchive the artifact
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: create env variables for npm configuration
  shell: |
    echo "NODE_ENV=production" > .env
    echo "VERSION=1" >> .env
    echo "TYPEORM_CONNECTION=postgres" >> .env
    echo "TYPEORM_MIGRATIONS_DIR=./src/migrations" >> .env
    echo "TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts" >> .env
    echo "TYPEORM_MIGRATIONS=./src/migrations/*.ts" >> .env
    echo "TYPEORM_HOST=$TYPEORM_HOST" >> .env
    echo "TYPEORM_PORT=$TYPEORM_PORT" >> .env
    echo "TYPEORM_USERNAME=$TYPEORM_USERNAME" >> .env
    echo "TYPEORM_PASSWORD=$TYPEORM_PASSWORD" >> .env
    echo "TYPEORM_DATABASE=$TYPEORM_DATABASE" >> .env
  args:
    chdir: ~/backend

- name: start app
  shell: |
    npm install
    pm2 delete all
    pm2 start npm -- start
  args:
    chdir: ~/backend