---

- name: update and upgrade packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: remove unneeded dependencies
  become: true
  apt:
    autoremove: yes

- name: install dependencies
  become: true
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: Copy artifact.tar.gz to EC2
  copy:
    src: "files/artifact.tar.gz"
    dest: "~/"

- name: extract artifact
  become: true
  unarchive:
    src: "files/artifact.tar.gz"
    dest: "~/"

- name: start app
  become: yes
  shell: |
    npm install
    pm2 delete all
    pm2 start npm -- start